[package]
name = "catan"
version = "0.1.0"
authors = ["Quentin Gendre <swynfel@gmail.com>"]
edition = "2018"

[dependencies.once_cell]
version = "1.3"

[dependencies.rand]
version = "0.7"
features = ["small_rng"]
